### ISSUE TITLE
question regarding implementation in gradcam.py

### ISSUE THREAD

**Issue by tumble-weed** [neouyghur/SESS#2]
hi,
thanks for releasing your code.  I had a question regarding gradcam.py:
In [line 32-35](https://github.com/neouyghur/SESS/blob/2f62f41fd67826bc5a027bdc9502a299b20748cf/cam/gradcam.py#L32)
```
        for i, item in enumerate(score):
            item.backward(retain_graph=retain_graph)
            gradients = self.gradients['value'].data[i]
            gradients_list.append(gradients)
```
it seems the gradients of the patches are being captured one patch at a time, instead of in a full batch fashion. upon benchmarking , this loop eats up some time. i wanted to know if there is a reason behind this choice that i might not be getting, or if a batched gradient would do just as well. something like:
```
score.sum().backward()
gradients = self.gradients['value'].data
``` 
thanks

**Comment by neouyghur** [comment]
hi @tumble-weed. It is a good question. I think GradCam does not support batch processes.  `score.sum().backward()` only returns the average gradient, but item based gradient is expected.

However, there might be some other ways to avoid the for loop, but I don't know. Pytorch form might be a good place to ask for help.
